lib: [
  "_build/install/default/lib/blake2/META" {"META"}
  "_build/install/default/lib/blake2/blake2.a" {"blake2.a"}
  "_build/install/default/lib/blake2/blake2.cma" {"blake2.cma"}
  "_build/install/default/lib/blake2/blake2.cmi" {"blake2.cmi"}
  "_build/install/default/lib/blake2/blake2.cmt" {"blake2.cmt"}
  "_build/install/default/lib/blake2/blake2.cmti" {"blake2.cmti"}
  "_build/install/default/lib/blake2/blake2.cmx" {"blake2.cmx"}
  "_build/install/default/lib/blake2/blake2.cmxa" {"blake2.cmxa"}
  "_build/install/default/lib/blake2/blake2.cmxs" {"blake2.cmxs"}
  "_build/install/default/lib/blake2/blake2.dune" {"blake2.dune"}
  "_build/install/default/lib/blake2/blake2.ml" {"blake2.ml"}
  "_build/install/default/lib/blake2/blake2.mli" {"blake2.mli"}
  "_build/install/default/lib/blake2/libblake2_stubs.a" {"libblake2_stubs.a"}
  "_build/install/default/lib/blake2/opam" {"opam"}
]
stublibs: [
  "_build/install/default/lib/stublibs/dllblake2_stubs.so"
]
