lib: [
  "_build/install/default/lib/hacl/META" {"META"}
  "_build/install/default/lib/hacl/hacl.a" {"hacl.a"}
  "_build/install/default/lib/hacl/hacl.cma" {"hacl.cma"}
  "_build/install/default/lib/hacl/hacl.cmi" {"hacl.cmi"}
  "_build/install/default/lib/hacl/hacl.cmt" {"hacl.cmt"}
  "_build/install/default/lib/hacl/hacl.cmti" {"hacl.cmti"}
  "_build/install/default/lib/hacl/hacl.cmx" {"hacl.cmx"}
  "_build/install/default/lib/hacl/hacl.cmxa" {"hacl.cmxa"}
  "_build/install/default/lib/hacl/hacl.cmxs" {"hacl.cmxs"}
  "_build/install/default/lib/hacl/hacl.dune" {"hacl.dune"}
  "_build/install/default/lib/hacl/hacl.ml" {"hacl.ml"}
  "_build/install/default/lib/hacl/hacl.mli" {"hacl.mli"}
  "_build/install/default/lib/hacl/libhacl_stubs.a" {"libhacl_stubs.a"}
  "_build/install/default/lib/hacl/opam" {"opam"}
]
stublibs: [
  "_build/install/default/lib/stublibs/dllhacl_stubs.so"
]
