lib: [
  "_build/install/default/lib/uecc/META" {"META"}
  "_build/install/default/lib/uecc/libuecc_stubs.a" {"libuecc_stubs.a"}
  "_build/install/default/lib/uecc/opam" {"opam"}
  "_build/install/default/lib/uecc/uecc.a" {"uecc.a"}
  "_build/install/default/lib/uecc/uecc.cma" {"uecc.cma"}
  "_build/install/default/lib/uecc/uecc.cmi" {"uecc.cmi"}
  "_build/install/default/lib/uecc/uecc.cmt" {"uecc.cmt"}
  "_build/install/default/lib/uecc/uecc.cmti" {"uecc.cmti"}
  "_build/install/default/lib/uecc/uecc.cmx" {"uecc.cmx"}
  "_build/install/default/lib/uecc/uecc.cmxa" {"uecc.cmxa"}
  "_build/install/default/lib/uecc/uecc.cmxs" {"uecc.cmxs"}
  "_build/install/default/lib/uecc/uecc.dune" {"uecc.dune"}
  "_build/install/default/lib/uecc/uecc.ml" {"uecc.ml"}
  "_build/install/default/lib/uecc/uecc.mli" {"uecc.mli"}
]
stublibs: [
  "_build/install/default/lib/stublibs/dlluecc_stubs.so"
]
